# Name of the GitHub Actions workflow
name: Deploy to Cloudflare Pages

# Trigger the workflow on push events to the main branch
on:
  push:
    branches:
      - main # Change this to your main branch name if it's different

# Define the jobs for the workflow
jobs:
  deploy:
    # Use the latest version of Ubuntu as the runner
    runs-on: ubuntu-latest

    # Steps to execute in the workflow
    steps:
      # Step 1: Check out the repository code
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          # Fetch only the latest commit to speed up the build process
          fetch-depth: 1

      # Step 2: Set up the Node.js environment
      - name: Setup Node.js environment
        uses: actions/setup-node@v3
        with:
          # Specify the Node.js version to use
          node-version: '18'

      # Step 3: Install dependencies using Yarn
      - name: Install dependencies
        run: yarn install

      # Step 4: Build the project
      - name: Build the project
        run: yarn build # Adjust this if your build command is different

      # Step 5: Deploy to Cloudflare Pages using wrangler
      - name: Deploy to Cloudflare Pages
        run: |
          # Install wrangler globally
          yarn global add @cloudflare/wrangler
          # Publish the built files to Cloudflare Pages
          wrangler pages publish dist --project-name=my-cloudflare-project --branch main --commit-hash ${{ github.sha }}
        env:
          # Use a secret to store the Cloudflare API token securely
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
